name: Build

on:
  push:
    tags: v*

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test with nunit
      run: dotnet test --verbosity normal

    - name: Pack with nuget
      run: dotnet pack --configuration=Release -p:PackageVersion=$Env:GITHUB_REF.substring(11)

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./bin/Release/

    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'

    - name: Setup nuget config
      run: nuget.exe sources add -name github -source "https://nuget.pkg.github.com/apmem/index.json" -username ${{ github.actor }} -password ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to GitHub Packages
      run: |
           for f in ./artifacts/*.nupkg
           do
             nuget push $f -Source "github"
           done
      shell: bash